wkfow:
  auth: oa-auth
  wx: oa-wechat
  domain: http://yun.eqbidding.com
  plugin: /data/soft/plugins_linux
server:
  port: 18210
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /oa-wkflow
logging:
  level:
    root: info
    org.springfromework.web: info
    org.hibernate: info
eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.1.199:9001/eureka/ 
      defaultZone: http://yun.eqbidding.com:16000/eureka/  
spring:
  application:
    name: oa-wkflow
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      maxFileSize: "100MB"
      maxRequestSize: "100MB"      
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yun.eqbidding.com:3306/oa-wkflow?nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8
    username: fxd
    password: 123456
  activiti:
    database-schema-update: true
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false

## ribbon
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
