eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:16000/eureka/
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test.eqbidding.com:3306/oa-auth?nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8
    username: fxd
    password: 123456