auth:
  wkflow: oa-wkflow
  corpid: ww4b055f3bec10790d
  corpsecret: 
  department_id: 
  agent_id: 1000005
  wx: oa-wechat
server:
  port: 18201
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /oa-auth
logging:
  level:
    root: info
    org.springfromework.web: info
    org.hibernate: info
eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.1.199:9001/eureka/
      defaultZone: http://yun.eqbidding.com:16000/eureka/
spring:
  application:
    name: oa-auth
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      maxFileSize: "100MB"
      maxRequestSize: "100MB"      
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test.eqbidding.com:3306/oa-auth?nullCatalogMeansCurrent=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8
    username: fxd
    password: 123456
  #redis
  redis:
    host: localhost
    port: 6379
#    password:            #没密码就不用设置了
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
